//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public string MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string MaLoai { get; set; }
        public string MaNhanHieu { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string ThoiGianBaoHanh { get; set; }
        public string MaManHinh { get; set; }
        public string AmThanh { get; set; }
        public string Anh { get; set; }
        public string ChupAnh { get; set; }
    }
}
