//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SanPham
    {
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string MaLoai { get; set; }
        public string MaNhanHien { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> ThoiGianBaoHanh { get; set; }
        public string MaManHinh { get; set; }
        public string AmThanh { get; set; }
        public string Anh { get; set; }
        public string ChupAnh { get; set; }
    }
}
